=== labDAO/labdao-improvement-proposal/lrc-004-ecoli_protein_expression/metadata-schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1657623294.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"name",
		"description",
		"image",
		"properties"
	],
	"properties": {
		"name": {
			"$id": "#root/name", 
			"title": "Name", 
			"type": "string",
			"default": "",
			"examples": [
				"protein expression and purification in e.coli"
			],
			"pattern": "^.*$"
		},
		"description": {
			"$id": "#root/description", 
			"title": "Description", 
			"type": "string",
			"default": "",
			"examples": [
				"receive an amino acid sequence; express and purify a protein in e.coli; return quality control and sample information"
			],
			"pattern": "^.*$"
		},
		"image": {
			"$id": "#root/image", 
			"title": "Image", 
			"type": "string",
			"default": "",
			"examples": [
				""
			],
			"pattern": "^.*$"
		},
		"properties": {
			"$id": "#root/properties", 
			"title": "Properties", 
			"type": "object",
			"required": [
				"user",
				"parameters",
				"input"
			],
			"properties": {
				"user": {
					"$id": "#root/properties/user", 
					"title": "User", 
					"type": "string",
					"default": "",
					"examples": [
						"0x64BC15E0A5A12dDbe321EEDD832d057775D11F56"
					],
					"pattern": "^.*$"
				},
				"parameters": {
					"$id": "#root/properties/parameters", 
					"title": "Parameters", 
					"type": "string",
					"default": "",
					"examples": [
						"ipfs://QmaQv91AUmu4wDNiNc8exUrSrDnZ65YBdfsfdxSJSnJbcz"
					],
					"pattern": "^.*$"
				},
				"input": {
					"$id": "#root/properties/input", 
					"title": "Input", 
					"type": "string",
					"default": "",
					"examples": [
						"ipfs://QmaQv91AUmu4wDNiNc8exUrSrDnZ65YBEXuTrxSJSnJbcz"
					],
					"pattern": "^.*$"
				}
			}
		}

	}
}

=== labDAO/labdao-improvement-proposal/lip-001-ecoli_protein_expression/lip-001-ecoli_protein_expression-metadata-example.json
{
    "name": "protein expression and purification in e.coli", 
    "description": "receive an amino acid sequence; express and purify a protein in e.coli; return quality control and sample information",
    "image": "",
    "properties": {
        "user": "0x64BC15E0A5A12dDbe321EEDD832d057775D11F56",
        "parameters": "ipfs://QmaQv91AUmu4wDNiNc8exUrSrDnZ65YBdfsfdxSJSnJbcz",
        "input": "ipfs://QmaQv91AUmu4wDNiNc8exUrSrDnZ65YBEXuTrxSJSnJbcz"
    }
  }
